language: c

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq check libopenmpi-dev openmpi-bin

script: ./autogen.sh && ./configure --enable-tests && make && make check

compiler:
  - clang
  - gcc

notifications:
  email:
    - jonb@lanl.gov
